# CI/CD Workflow Contract
# This is the target workflow configuration for the CI/CD pipeline feature.
# File location: .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15 # FR-008: quality checks within 15 minutes
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # Version auto-detected from packageManager in package.json (8.15.0)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

  e2e:
    name: E2E Tests
    # Runs against dev-server started via Playwright's webServer config
    # (see packages/site/playwright.config.ts)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
      options: --user 1001 --ipc=host
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run E2E tests
        # Dev-server starts automatically via webServer config in playwright.config.ts
        run: pnpm test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    name: Deploy
    needs: [ci, e2e]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 20 # SC-003: deployment within 20 minutes
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication
    environment: production
    outputs:
      cloudfront_domain: ${{ steps.get-url.outputs.domain }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy CDK Stack
        id: cdk-deploy
        env:
          GITHUB_WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        working-directory: packages/infra
        run: npx cdk deploy --require-approval never -c environment=prod

      - name: Get CloudFront URL
        id: get-url
        run: |
          DOMAIN=$(aws cloudformation describe-stacks \
            --stack-name BlogStack \
            --query 'Stacks[0].Outputs[?OutputKey==`DistributionDomain`].OutputValue' \
            --output text)
          echo "domain=$DOMAIN" >> $GITHUB_OUTPUT

  smoke-test:
    name: Smoke Tests
    needs: deploy
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
      options: --user 1001 --ipc=host
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run smoke tests
        env:
          BASE_URL: https://${{ needs.deploy.outputs.cloudfront_domain }}
        run: pnpm test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: smoke-test-report
          path: playwright-report/
          retention-days: 30
